### PR TITLE
CoinMarketcapDataFetcher

### PR DESCRIPTION
**Pull request by DeProdigy**

### CODE REVIEW

**Review by DanielRakh — APPROVED** [review]

**Review by DanielRakh — CHANGES_REQUESTED** [review]
Let's move the state out of the constructor and get rid of it in Top100Screen

**Comment by DeProdigy** [comment]
We need the state of `coinMarketcapDataFetched` for the loading screen. This is why we're doing `coinMarketcapDataFetched: false` initially so the `Loading` indicator shows up first. We should have some loading component in the future that shows some loading animation.

**Comment by DanielRakh** [comment]
I meant to move the state out of the constructor so we can get rid of the constructor and write it like `state = { coinMarketcapDataFetched: false, coinMarketcapData: [],}`

**Comment by DeProdigy** [comment]
Great call. Bump.

**Review by DanielRakh — APPROVED** [review]

**Pull request merged**
